services:
  app:
    build:
      target: development
    volumes:
      - ./:/home/node/app
    ports:
      - "4200:4200"

  cli:
    build:
      target: cli

    tty: true
    volumes:
      - ./:/home/node/app
